# Generated by Django 4.2.27 on 2026-01-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji for the amenity', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text='Main description of the location'),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='location',
            name='how_to_apply',
            field=models.TextField(blank=True, help_text='How to apply section'),
        ),
        migrations.AddField(
            model_name='location',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='location',
            name='social_google_plus',
            field=models.URLField(blank=True, help_text='Google+ profile URL'),
        ),
        migrations.AddField(
            model_name='location',
            name='social_pinterest',
            field=models.URLField(blank=True, help_text='Pinterest profile URL'),
        ),
        migrations.AddField(
            model_name='location',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='location',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or video URL'),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL'),
        ),
        migrations.AddField(
            model_name='location',
            name='what_we_looking_for',
            field=models.TextField(blank=True, help_text="What we're looking for section"),
        ),
        migrations.AddField(
            model_name='location',
            name='why_this_matters',
            field=models.TextField(blank=True, help_text='Why this matters section'),
        ),
        migrations.AddField(
            model_name='location',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='locations', to='locations.amenity'),
        ),
    ]
