# Generated by Django 4.2.27 on 2026-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_amenity_location_description_location_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(help_text='Google Place ID', max_length=255)),
                ('place_name', models.CharField(blank=True, help_text='Place name for reference', max_length=200)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('quality_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('location_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('service_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('price_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('review_text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('hearts', models.IntegerField(default=0)),
                ('save_info', models.BooleanField(default=False, help_text='User wants to save info for next time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['place_id'], name='locations_r_place_i_136179_idx'), models.Index(fields=['created_at'], name='locations_r_created_265774_idx'), models.Index(fields=['is_active'], name='locations_r_is_acti_2b28fb_idx')],
            },
        ),
    ]
