# Generated by Django 4.2.27 on 2026-01-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='locations.review')),
            ],
            options={
                'verbose_name_plural': 'Review Replies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['review'], name='locations_r_review__3e06ae_idx'), models.Index(fields=['created_at'], name='locations_r_created_50d02c_idx'), models.Index(fields=['is_active'], name='locations_r_is_acti_08d097_idx')],
            },
        ),
    ]
