# Generated by Django 4.2.27 on 2026-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreply',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
