# Generated by Django 4.2.27 on 2026-01-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_reviewreply_dislikes_reviewreply_hearts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, help_text='Parent reply if this is a nested reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='locations.reviewreply'),
        ),
    ]
