# Generated by Django 4.2.7 on 2026-01-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_reviewreply_parent_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sponsor name/title', max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly name (e.g., 'genz-marketing')", max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Sponsor logo/image for card', null=True, upload_to='sponsors/')),
                ('short_description', models.TextField(blank=True, help_text='Short description for card view')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL')),
                ('sponsor_spotlight_title', models.CharField(blank=True, help_text='Sponsor Spotlight heading', max_length=300)),
                ('sponsor_spotlight_description', models.TextField(blank=True, help_text='Sponsor Spotlight description')),
                ('why_partner_title', models.CharField(blank=True, help_text='Why AccessAdvisr Partners heading', max_length=300)),
                ('why_partner_description', models.TextField(blank=True, help_text='Why AccessAdvisr Partners description')),
                ('services_title', models.CharField(blank=True, default='Services', help_text='Services section title', max_length=300)),
                ('services_description', models.TextField(blank=True, help_text='Services list (one per line or formatted text)')),
                ('why_sponsor_title', models.CharField(blank=True, help_text='Why AccessAdvisr is Sponsored heading', max_length=300)),
                ('why_sponsor_description', models.TextField(blank=True, help_text='Why AccessAdvisr is Sponsored description')),
                ('connect_title', models.CharField(blank=True, help_text='Connect section title', max_length=300)),
                ('connect_description', models.TextField(blank=True, help_text='Connect section description')),
                ('website_url', models.URLField(blank=True, help_text='Official website URL')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['status', 'order'], name='locations_s_status_d7d383_idx'), models.Index(fields=['slug'], name='locations_s_slug_44f693_idx')],
            },
        ),
    ]
