# Generated by Django 4.2.7 on 2026-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name (auto-generated from name if left blank)', max_length=200, unique=True),
        ),
    ]
