# Generated by Django 4.2.7 on 2026-01-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_sponsor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(blank=True, help_text='Sponsor logo/image for card (will be saved in static/images/sponsor_card/)', null=True, upload_to='images/sponsor_card/'),
        ),
    ]
