# Generated by Django 4.2.7 on 2026-01-13 09:22

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_sponsor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(blank=True, help_text='Sponsor logo/image for card (will be saved in static/images/partner_card/)', null=True, upload_to=locations.models.partner_image_upload_path),
        ),
    ]
