# Generated by Django 4.2.7 on 2026-01-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_sponsor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('comment_text', models.TextField()),
                ('save_info', models.BooleanField(default=False, help_text='Save name, email for next time')),
                ('is_approved', models.BooleanField(default=False, help_text='Comment is approved and visible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='locations.sponsor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('reply_text', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Reply is approved and visible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='locations.sponsorcomment')),
                ('parent_reply', models.ForeignKey(blank=True, help_text='Parent reply if this is a nested reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='locations.sponsorcommentreply')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['comment', 'is_approved'], name='locations_s_comment_523aed_idx'), models.Index(fields=['created_at'], name='locations_s_created_2a15f3_idx'), models.Index(fields=['is_active'], name='locations_s_is_acti_7e52b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sponsorcomment',
            index=models.Index(fields=['sponsor', 'is_approved'], name='locations_s_sponsor_f577bd_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcomment',
            index=models.Index(fields=['created_at'], name='locations_s_created_ddb584_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcomment',
            index=models.Index(fields=['is_active'], name='locations_s_is_acti_1ea8ef_idx'),
        ),
    ]
