# Generated by Django 4.2.7 on 2026-01-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_sponsorcomment_sponsorcommentreply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name (auto-generated from title if left blank)', max_length=300, unique=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for blog card and detail page', null=True, upload_to='images/blogs/')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt/summary for blog card')),
                ('content', models.TextField(help_text='Full blog post content (HTML supported)')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL (optional)')),
                ('video_title', models.CharField(blank=True, help_text='Video title if video is provided', max_length=300)),
                ('author_name', models.CharField(default='AccessAdvisr', help_text='Author name', max_length=100)),
                ('author_avatar', models.ImageField(blank=True, help_text='Author avatar image', null=True, upload_to='images/blogs/authors/')),
                ('faqs', models.JSONField(blank=True, default=list, help_text="List of FAQs with 'question' and 'answer' keys")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured blog (appears first)')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO meta keywords', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date (auto-set when status changes to published)', null=True)),
            ],
            options={
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('comment_text', models.TextField()),
                ('save_info', models.BooleanField(default=False, help_text='Save name, email for next time')),
                ('is_approved', models.BooleanField(default=False, help_text='Comment is approved and visible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='locations.blog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('reply_text', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Reply is approved and visible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='locations.blogcomment')),
                ('parent_reply', models.ForeignKey(blank=True, help_text='Parent reply if this is a nested reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='locations.blogcommentreply')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'is_featured'], name='locations_b_status_b45982_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='locations_b_slug_787cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['published_at'], name='locations_b_publish_b1e1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcommentreply',
            index=models.Index(fields=['comment', 'is_approved'], name='locations_b_comment_66ecdd_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcommentreply',
            index=models.Index(fields=['created_at'], name='locations_b_created_6c1179_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcommentreply',
            index=models.Index(fields=['is_active'], name='locations_b_is_acti_61ed41_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['blog', 'is_approved'], name='locations_b_blog_id_b057fb_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['created_at'], name='locations_b_created_ce0a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['is_active'], name='locations_b_is_acti_036b58_idx'),
        ),
    ]
