# Generated by Django 4.2.7 on 2026-01-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_blog_blogcomment_blogcommentreply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='locations_b_status_b45982_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='locations_b_publish_b1e1a8_idx',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_avatar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['created_at'], name='locations_b_created_573954_idx'),
        ),
    ]
