# Generated by Django 4.2.7 on 2026-01-13 12:16

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='AccessAdvisr', help_text='Author name', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Blog featured image', null=True, upload_to=locations.models.blog_image_upload_path),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Blog status', max_length=10),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'created_at'], name='locations_b_status_76b999_idx'),
        ),
    ]
