# Generated by Django 4.2.7 on 2026-01-13 12:39

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_blog_author_blog_image_blog_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Partner post title', max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name (auto-generated from title if left blank)', max_length=300, unique=True)),
                ('author', models.CharField(default='AccessAdvisr', help_text='Author name', max_length=100)),
                ('content', models.TextField(help_text='Full partner post content (HTML supported)')),
                ('image', models.ImageField(blank=True, help_text='Partner featured image', null=True, upload_to=locations.models.partner_image_upload_path)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL')),
                ('website_url', models.URLField(blank=True, help_text='Partner website URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Partner post status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='locations_p_slug_8221c9_idx'), models.Index(fields=['status', 'created_at'], name='locations_p_status_7483e9_idx'), models.Index(fields=['created_at'], name='locations_p_created_d3cc0c_idx')],
            },
        ),
    ]
