# Generated by Django 4.2.7 on 2026-01-13 12:47

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'title']},
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='locations_p_status_7483e9_idx',
        ),
        migrations.AddField(
            model_name='partner',
            name='connect_description',
            field=models.TextField(blank=True, help_text='Connect section description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='connect_title',
            field=models.CharField(blank=True, help_text='Connect section title', max_length=300),
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_spotlight_description',
            field=models.TextField(blank=True, help_text='Partner Spotlight description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_spotlight_title',
            field=models.CharField(blank=True, help_text='Partner Spotlight heading', max_length=300),
        ),
        migrations.AddField(
            model_name='partner',
            name='services_description',
            field=models.TextField(blank=True, help_text='Services list (one per line or formatted text)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='services_title',
            field=models.CharField(blank=True, default='Services', help_text='Services section title', max_length=300),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description for card view'),
        ),
        migrations.AddField(
            model_name='partner',
            name='why_partner_description',
            field=models.TextField(blank=True, help_text='Why AccessAdvisr Partners description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='why_partner_title',
            field=models.CharField(blank=True, help_text='Why AccessAdvisr Partners heading', max_length=300),
        ),
        migrations.AddField(
            model_name='partner',
            name='why_supports_description',
            field=models.TextField(blank=True, help_text='Why Partner Supports AccessAdvisr description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='why_supports_title',
            field=models.CharField(blank=True, help_text='Why Partner Supports AccessAdvisr heading', max_length=300),
        ),
        migrations.AlterField(
            model_name='partner',
            name='content',
            field=models.TextField(blank=True, help_text='Full partner post content (HTML supported)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, help_text='Partner logo/image for card', null=True, upload_to=locations.models.partner_image_upload_path),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', help_text='Partner post status', max_length=10),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website URL'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['status', 'order'], name='locations_p_status_d7139e_idx'),
        ),
    ]
