# Generated by Django 4.2.7 on 2026-01-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_migrate_sponsor_to_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('comment_text', models.TextField()),
                ('save_info', models.BooleanField(default=False, help_text='Save name, email for next time')),
                ('is_approved', models.BooleanField(default=False, help_text='Comment is approved and visible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='locations.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('reply_text', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Reply is approved and visible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='locations.partnercomment')),
                ('parent_reply', models.ForeignKey(blank=True, help_text='Parent reply if this is a nested reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='locations.partnercommentreply')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['comment', 'is_approved'], name='locations_p_comment_ef4f24_idx'), models.Index(fields=['created_at'], name='locations_p_created_a642ab_idx'), models.Index(fields=['is_active'], name='locations_p_is_acti_e9391e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='partnercomment',
            index=models.Index(fields=['partner', 'is_approved'], name='locations_p_partner_71a523_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercomment',
            index=models.Index(fields=['created_at'], name='locations_p_created_4510af_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercomment',
            index=models.Index(fields=['is_active'], name='locations_p_is_acti_419980_idx'),
        ),
    ]
