# Generated by Django 4.2.7 on 2026-01-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_partnercomment_partnercommentreply_and_more'),
    ]

    operations = [
        # Delete models directly - Django will handle dependencies automatically
        migrations.DeleteModel(
            name='SponsorCommentReply',
        ),
        migrations.DeleteModel(
            name='SponsorComment',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
