# Generated by Django 4.2.7 on 2026-01-14 06:00

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_remove_sponsor_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='About post title', max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name (auto-generated from title if left blank)', max_length=300, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Featured image for the post', null=True, upload_to=locations.models.about_post_image_upload_path)),
                ('content', models.TextField(help_text='Full post content (HTML supported)')),
                ('share_this_post', models.BooleanField(default=True, help_text='Show share buttons for this post')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Post status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Post',
                'verbose_name_plural': 'About Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='locations_a_slug_e120a9_idx'), models.Index(fields=['status', 'created_at'], name='locations_a_status_05dd83_idx'), models.Index(fields=['created_at'], name='locations_a_created_02dfbf_idx')],
            },
        ),
    ]
