# Generated by Django 4.2.7 on 2026-01-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_aboutpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('comment_text', models.TextField()),
                ('save_info', models.BooleanField(default=False, help_text='Save name, email for next time')),
                ('is_approved', models.BooleanField(default=False, help_text='Comment is approved and visible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='locations.aboutpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('reply_text', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Reply is approved and visible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='locations.aboutcomment')),
                ('parent_reply', models.ForeignKey(blank=True, help_text='Parent reply if this is a nested reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='locations.aboutcommentreply')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['comment', 'is_approved'], name='locations_a_comment_e48929_idx'), models.Index(fields=['created_at'], name='locations_a_created_0bfd55_idx'), models.Index(fields=['is_active'], name='locations_a_is_acti_5b135d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aboutcomment',
            index=models.Index(fields=['about_post', 'is_approved'], name='locations_a_about_p_e6f48f_idx'),
        ),
        migrations.AddIndex(
            model_name='aboutcomment',
            index=models.Index(fields=['created_at'], name='locations_a_created_904794_idx'),
        ),
        migrations.AddIndex(
            model_name='aboutcomment',
            index=models.Index(fields=['is_active'], name='locations_a_is_acti_a9c0e0_idx'),
        ),
    ]
