# Generated by Django 4.2.7 on 2026-01-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_aboutcomment_aboutcommentreply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpost',
            name='share_email_url',
            field=models.URLField(blank=True, help_text='Custom Email share URL (leave blank to use default)'),
        ),
        migrations.AddField(
            model_name='aboutpost',
            name='share_facebook_url',
            field=models.URLField(blank=True, help_text='Custom Facebook share URL (leave blank to use default)'),
        ),
        migrations.AddField(
            model_name='aboutpost',
            name='share_linkedin_url',
            field=models.URLField(blank=True, help_text='Custom LinkedIn share URL (leave blank to use default)'),
        ),
        migrations.AddField(
            model_name='aboutpost',
            name='share_twitter_url',
            field=models.URLField(blank=True, help_text='Custom Twitter/X share URL (leave blank to use default)'),
        ),
    ]
