# Generated by Django 4.2.7 on 2026-01-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_aboutpost_share_email_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpost',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'About Post', 'verbose_name_plural': 'About Posts'},
        ),
        migrations.AddField(
            model_name='aboutpost',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
