# Generated by Django 4.2.7 on 2026-01-14 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0023_alter_aboutpost_options_aboutpost_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign title', max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=300, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Campaign image', null=True, upload_to='images/donations/')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target donation amount', max_digits=10)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount raised so far', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Campaign description')),
                ('is_active', models.BooleanField(default=True, help_text='Is this campaign active?')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation Campaign',
                'verbose_name_plural': 'Donation Campaigns',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='locations_d_slug_f0a0ee_idx'), models.Index(fields=['is_active', 'order'], name='locations_d_is_acti_347e47_idx')],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Donor name', max_length=200)),
                ('email', models.EmailField(help_text='Donor email address', max_length=254)),
                ('phone', models.CharField(help_text='Donor phone number', max_length=20)),
                ('street_address', models.CharField(blank=True, help_text='Street address', max_length=300)),
                ('apartment_suite', models.CharField(blank=True, help_text='Apartment, suite, etc', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state_province', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('zip_postal_code', models.CharField(blank=True, help_text='ZIP / Postal Code', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100)),
                ('donation_amount', models.CharField(choices=[('5', '£5'), ('10', '£10'), ('other', 'Other')], help_text='Donation amount option', max_length=10)),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Custom donation amount (if 'Other' selected)", max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], help_text='Payment method', max_length=20)),
                ('consent_given', models.BooleanField(default=False, help_text='Consent that information is accurate')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Donation status', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment transaction ID', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Associated campaign (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='locations.donationcampaign')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign'], name='locations_d_campaig_683c31_idx'), models.Index(fields=['status'], name='locations_d_status_c8df5a_idx'), models.Index(fields=['created_at'], name='locations_d_created_60b055_idx'), models.Index(fields=['email'], name='locations_d_email_485f3c_idx')],
            },
        ),
    ]
