# Generated by Django 4.2.7 on 2026-01-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0025_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
