# Generated by Django 4.2.7 on 2026-01-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0026_location_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address', max_length=300),
        ),
    ]
