# Generated by Django 4.2.7 on 2026-01-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0027_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rating out of 5.00', max_digits=3),
        ),
    ]
