# Generated by Django 4.2.7 on 2026-01-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0029_location_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, help_text='Location/Business image', null=True, upload_to='locations/'),
        ),
    ]
