# Generated by Django 4.2.7 on 2026-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0031_add_user_to_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person contacting', max_length=200)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', help_text='Message status', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='locations_c_status_b2e4ec_idx'), models.Index(fields=['created_at'], name='locations_c_created_653acf_idx'), models.Index(fields=['email'], name='locations_c_email_527250_idx')],
            },
        ),
    ]
