# Generated by Django 4.2.7 on 2026-01-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0032_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Place ID if linked to Google Maps', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=250, unique=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['slug'], name='locations_l_slug_73d9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['place_id'], name='locations_l_place_i_ebc939_idx'),
        ),
    ]
